version: '3.8'
services:
  kho-manager:
    build: .
    container_name: kho-manager
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./shorts:/app/shorts
      - ./overlay:/app/overlay
    environment:
      - PYTHONUNBUFFERED=1
